

seq = "ATGATAGTCGCATATGCCAGTCGGAGCTAGCATAGACTGCCCGTCGCAGTCACGTCTCCGATCAATGGAAAGGGATCGCTGCCATGCTCTCGAGCCGTTCCACTCACAGAGCAGCGGAGCCGACATTTCGCATCGCCGTCATGAGTGGGCGTGAGGGGTTATTATGTTATTGGGAGTGATAATCATCCCGACCATGCATTACACTATGGAGATGCTGTTTTACTGACTCGGTTGCGAGCTTAAGGAGTTCTTCTCGTCCAAAAAATTAGGTAGTGGGTAATCCGGTTGTGGGCGCGACAGAGGGGGTGTGATACGGACTTGGAATATACCCAGGACTACGATTTACGCACCGGCAGCCTGGTCGCATTGCGAGGGTCCGTTTCACCGCTAGCGACCGGAAAACGCCGGCCTGCCACTGGCCAAGATGAGGCGCTTTATGAGGGCGATTCTATACCCGAAAGCCACTGTGCAGGCATGGTCCCCGATCTTTATCCATGCGCGCCTACGTTCTAGAGCCAAACGATGCTCGCCATTAAGCACGATGGACGCATAGACGCAAGTGTCAGGCATTCAGCTGCATCCGGATTGTGCTACCTGTCCTGCATCCACTCCATCGGGCCCAAACCAAGTAGCGCGCATGATGACAAACTGAATGGGAAGTATTGCCCTCTTGCCCCGAGCACCTTTGCATTCCCAAAAGTCTACGGCAGGCCTCTCAAGGCGGTCCACGAAGACTTGTAGTATTCGGGCACAATGGGCCGGCAGCCGAAATAGCTTGCAGTTGGGTGAAGAGATAACTACACCAAGTAATTGCACATGGCGCTGGACCTGGCCATTGATCACTGAGATTTACACGGGGGCAGCAGCCGGTGAGTTTGGGTGTGCCCCACCGCCATGATGCTTGCTTAGGGGGATTAGGGCATCAAAGATCATACTATCAAGCGCCTTGAGATGGATGGTAATA"

def CountNucleotideFreq(seq):
	tempSeq = {"A":0,"C":0,"G":0,"T":0}
	for nucleotide in seq:
		tempSeq[nucleotide] += 1
	A = str(tempSeq["A"])
	C = str(tempSeq["C"])
	G = str(tempSeq["G"])
	T = str(tempSeq["T"])	
	print(A  + " " + C  + " " + G + " " + T)	
CountNucleotideFreq(seq)	